module.exports = {
    orignal: [
      'index',
      {type: 'ref', id: 'note', label: 'Note ページ'},
      {type: 'ref', id: 'wiki', label: 'Wiki ページ'},
    ],
    wiki: [
      {type: 'ref', id: 'index', label: '↩︎ トップ ページ'},
      {type: 'ref', id: 'note', label: '↩︎ Note ページ'},
      'wiki',
      {
        type: 'autogenerated',
        dirName: 'wiki', // '.' means the current docs folder
      },
    ],
    note: [
      {type: 'ref', id: 'index', label: '↩︎ トップ ページ'},
      {type: 'ref', id: 'wiki', label: '↩︎ Wiki ページ'},
      'note',
      {
        type: 'autogenerated',
        dirName: 'note', // '.' means the current docs folder
      },
    ],
  };
