module.exports = {
    orignal: [
      'index',
      {type: 'ref', id: 'note', label: 'Note ページ'},
      {type: 'ref', id: 'wikinote', label: 'WikiNote ページ'},
      {type: 'ref', id: 'wiki', label: 'Wiki ページ'},
    ],
    wiki: [
      {type: 'ref', id: 'index', label: '↩︎ トップ ページ'},
      'wiki',
      {
        type: 'autogenerated',
        dirName: 'wiki', // '.' means the current docs folder
      },
    ],
    note: [
      {type: 'ref', id: 'index', label: '↩︎ トップ ページ'},
      'note',
      {
        type: 'autogenerated',
        dirName: 'note', // '.' means the current docs folder
      },
    ],
    wikinote: [
      {type: 'ref', id: 'index', label: '↩︎ トップ ページ'},
      'wikinote',
      {
        type: 'autogenerated',
        dirName: 'wikinote', // '.' means the current docs folder
      },
    ],
  };
