module.exports = {
    top: [
      {
        type: 'autogenerated',
        dirName: '.', // '.' means the current docs folder
      },
      {type: 'ref', id: 's1707/index', label: 'S1707'},
    ],
    s1707: [
      {type: 'ref', id: 'index', label: 'サーバー トップ'},
      {
        type: 'autogenerated',
        dirName: 's1707', // '.' means the current docs folder
      },
      {type: 'ref', id: 's1707/MatE/index', label: 'MatE トップ'},
      {type: 'ref', id: 's1707/JCAP/index', label: 'JCAP トップ'},
    ],

    // 連盟に関する情報
    MatE: [
      {type: 'ref', id: 'index', label: 'サーバー トップ'},
      {type: 'ref', id: 's1707/index', label: 'S1707 トップ'},
      {
        type: 'autogenerated',
        dirName: 's1707/MatE', // '.' means the current docs folder
      },
    ],
    JCAP: [
      {type: 'ref', id: 'index', label: 'サーバー トップ'},
      {type: 'ref', id: 's1707/index', label: 'S1707 トップ'},
      {
        type: 'autogenerated',
        dirName: 's1707/JCAP', // '.' means the current docs folder
      },
    ],
  };
