module.exports = {
    top: [
      'index',
      {
        'サーバー ページ': [{type: 'ref', id: 's1707/index', label: 'S1707'}],
      },
    ],

    // サーバー
    s1707: [
      {type: 'ref', id: 'index', label: '↩︎ サーバー トップ'},
      {
        type: 'autogenerated',
        dirName: 's1707', // '.' means the current docs folder
      },
      {
        '連盟 ページ': [{type: 'ref', id: 's1707/MatE/index', label: 'MatE'}, {type: 'ref', id: 's1707/JCAP/index', label: 'JCAP'}],
      },
    ],

    // 連盟
    MatE: [
      {type: 'ref', id: 'index', label: '<span class="fa-light fa-caret-left"></span> サーバー トップ'},
      {type: 'ref', id: 's1707/index', label: '↩︎ S1707 トップ'},
      {
        type: 'autogenerated',
        dirName: 's1707/MatE', // '.' means the current docs folder
      },
    ],
    JCAP: [
      {type: 'ref', id: 'index', label: '↩︎ サーバー トップ'},
      {type: 'ref', id: 's1707/index', label: '↩︎ S1707 トップ'},
      {
        type: 'autogenerated',
        dirName: 's1707/JCAP', // '.' means the current docs folder
      },
    ],
  };
