module.exports = {
    Sidebar: [
      "index",
      {
        '世界': {
          '暗黒軍/敵': [
            {
              type: 'autogenerated',
              dirName: './world/npc', // '.' means the current docs folder
            },
          ],
        },
      },
    ],

    Event: [
      {
        type: 'autogenerated',
        dirName: './event', // '.' means the current docs folder
      },
    ],
  };