# https://qiita.com/taquaki-satwo/items/294e02aa272a7a2392ca
name: Compress images
on:
  pull_request:
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Compress Images
        uses: calibreapp/image-actions@master
        with:
          githubToken: ${{ secrets.METRICS_TOKEN }}
          jpegQuality: "80"
          pngQuality: "80"
          webpQuality: "80"
